<?php

 function fonts(){

    $fonts  =   array(
            'default'					                  => 'Default',
            '\'Abril Fatface\', cursive'					=> '\'Abril Fatface\', cursive',
            '\'Actor\',sans-serif'						   => '\'Actor\', sans-serif',
            '\'Alegreya Sans\', sans-serif'				=> '\'Alegreya Sans\', sans-serif',
            '\'Alegreya Sans SC\', sans-serif'			=> '\'Alegreya Sans\', sans-serif',
            '\'Alegreya\', serif'							=> '\'Alegreya\', serif',
            '\'Alegreya SC\', serif'						=> '\'Alegreya SC\', serif',
            '\'Anonymous Pro\', monospace'				=> '\'Anonymous Pro\', monospace',
            '\'Arvo\', serif'								   => '\'Arvo\', serif',
            '\'Arimo\', sans-serif'						   => '\'Arimo\', sans-serif',
            '\'Archivo\', sans-serif'						=> '\'Archivo\', sans-serif',
            '\'Archivo Narrow\', sans-serif'				=> '\'Archivo Narrow\', sans-serif',
            '\'Archivo Black\', sans-serif'				=> '\'Archivo Black\', sans-serif',
            '\'BioRhyme\', serif'							=> '\'BioRhyme\', serif',
            '\'Biryani\', sans-serif'						=> '\'Biryani\', sans-serif',
            '\'B612 Mono\', monospace'                => '\'B612 Mono\', monospace',
            '\'Cabin\', sans-serif'						   => '\'Cabin\', sans-serif',
            '\'Cabin Condensed\', sans-serif'			=> '\'Cabin Condensed\', sans-serif',
            '\'Cardo\', serif'							   => '\'Cardo\', serif',
            '\'Chivo\', sans-serif'						   => '\'Chivo\', sans-serif',
            '\'Contrail One\', cursive'					=> '\'Contrail One\', cursive',
            '\'Cormorant\', serif'						   => '\'Cormorant\', serif',
            '\'Cormorant Garamond\', serif'				=> '\'Cormorant Garamond\', serif',
            '\'Cormorant Infant\', serif'					=> '\'Cormorant Infant\', serif',
            '\'Concert One\', cursive'					   => '\'Concert One\', cursive',
            '\'Cormorant SC\', serif'						=> '\'Cormorant SC\', serif',
            '\'Cormorant Unicase\', serif'				=> '\'Cormorant Unicase\', serif',
            '\'Cormorant Upright\', serif'				=> '\'Cormorant Upright\', serif',
            '\'Crimson Text\', serif'						=> '\'Crimson Text\', serif',
            '\'Dosis\', sans-serif'						   => '\'Dosis\', sans-serif',
            '\'Domine\', serif'							   => '\'Domine\', serif',
            '\'Exo\', sans-serif'							=> '\'Exo\', sans-serif',
            '\'Exo 2\', sans-serif'						   => '\'Exo 2\', sans-serif',
            '\'Eczar\', serif'							   => '\'Eczar\', serif',
            '\'Fira Sans\', sans-serif'					=> '\'Fira Sans\', sans-serif',
            '\'Fira Sans Condensed\', sans-serif'		=> '\'Fira Sans Condensed\', sans-serif',
            '\'Frank Ruhl Libre\', serif'					=> '\'Frank Ruhl Libre\', serif',
            '\'Fugaz One\', cursive'						=> '\'Fugaz One\', cursive',
            '\'IBM Plex Mono\', monospace'            => '\'IBM Plex Mono\', monospace',
            '\'IBM Plex Sans\', sans-serif'				=> '\'IBM Plex Sans\', sans-serif',
            '\'IBM Plex Sans Condensed\', sans-serif'	=> '\'IBM Plex Sans Condensed\', sans-serif',
            '\'IBM Plex Serif\', serif'					=> '\'IBM Plex Serif\', serif',
            '\'Inconsolata\', monospace'					=> '\'Inconsolata\', monospace',
            '\'Inknut Antiqua\', serif'					=> '\'Inknut Antiqua\', serif',
            '\'Josefin Sans\', sans-serif'				=> '\'Josefin Sans\', sans-serif',
            '\'Karla\', sans-serif'						   => '\'Karla\', sans-serif',
            "'Kaushan Script', cursive"					=> '\'Kaushan Script\', cursive',
            '\'Lato\', sans-serif'						   => '\'Lato\', sans-serif',
            '\'Libre Baskerville\', serif'				=> '\'Libre Baskerville\', serif',
            '\'Libre Franklin\', sans-serif'				=> '\'Libre Franklin\', sans-serif',
            '\'Lora\', serif'								   => '\'Lora\', serif',
            '\'Major Mono Display\', monospace'       => '\'Major Mono Display\', monospace',
            '\'Martel Sans\', sans-serif'					=> '\'Martel Sans\', sans-serif',
            '\'Marck Script\', cursive'					=> '\'Marck Script\', cursive',
            '\'Merriweather\', serif'						=> '\'Merriweather\', serif',
            '\'Merriweather Sans\', sans-serif'			=> '\'Merriweather Sans\', sans-serif',
            '\'Monofett\', cursive'                   => '\'Monofett\', cursive',
            '\'Montserrat\', sans-serif'					=> '\'Montserrat\', sans-serif',
            '\'Montserrat Alternates\', sans-serif'	=> '\'Montserrat Alternates\', sans-serif',
            '\'Mukta\', sans-serif'						   => '\'Mukta\', sans-serif',
            '\'Muli\', sans-serif'						   => '\'Muli\', sans-serif',
            '\'Nanum Gothic\', sans-serif'				=> '\'Nanum Gothic\', sans-serif',
            '\'Neuton\', serif'							   => '\'Neuton\', serif',
            '\'Noto Sans\', sans-serif'					=> '\'Noto Sans\', sans-serif',
            '\'Noto Sans JP\', sans-serif'				=> '\'Noto Sans JP\', sans-serif',
            '\'Noto Sans KR\', sans-serif'				=> '\'Noto Sans KR\', sans-serif',
            '\'Noto Sans SC\', sans-serif'				=> '\'Noto Sans SC\', sans-serif',
            '\'Noto Sans TC\', sans-serif'				=> '\'Noto Sans TC\', sans-serif',
            '\'Noto Serif\', serif'						   => '\'Noto Serif\', serif',
            '\'Noto Serif JP\', serif'					   => '\'Noto Serif JP\', serif',
            '\'Noto Serif KR\', serif'					   => '\'Noto Serif KR\', serif',
            '\'Noto Serif SC\', serif'					   => '\'Noto Serif SC\', serif',
            '\'Noto Serif TC\', serif'					   => '\'Noto Serif TC\', serif',
            '\'Nunito\', sans-serif'					   => '\'Nunito\', sans-serif',
            '\'Nunito Sans\', sans-serif'					=> '\'Nunito Sans\', sans-serif',
            '\'Old Standard TT\', serif'					=> '\'Old Standard TT\', serif',
            '\'Oleo Script\', cursive'					   => '\'Oleo Script\', cursive',
            '\'Open Sans\', sans-serif'					=> '\'Open Sans\', sans-serif',
            '\'Open Sans Condensed\', sans-serif'		=> '\'Open Sans Condensed\', sans-serif',
            '\'Oswald\', sans-serif'						=> '\'Oswald\', sans-serif',
            '\'Overpass Mono\', monospace'            => '\'Overpass Mono\', monospace',
            '\'Oxygen\', sans-serif'						=> '\'Oxygen\', sans-serif',
            '\'Petit Formal Script\', cursive'			=> '\'Petit Formal Script\', cursive',
            '\'Pinyon Script\', cursive'					=> '\'Pinyon Script\', cursive',
            '\'Playball\', cursive'						   => '\'Playball\', cursive',
            '\'Playfair Display\', serif'					=> '\'Playfair Display\', serif',
            '\'Playfair Display SC\', serif'				=> '\'Playfair Display SC\', serif',
            '\'Poppins\', sans-serif'						=> '\'Poppins\', sans-serif',
            '\'Prompt\', sans-serif'						=> '\'Prompt\', sans-serif',
            '\'PT Sans\', sans-serif'						=> '\'PT Sans\', sans-serif',
            '\'PT Serif\', serif'							=> '\'PT Serif\', serif',
            '\'PT Sans Caption\', sans-serif'			=> '\'PT Sans Caption\', sans-serif',
            '\'PT Serif Caption\', serif'					=> '\'PT Serif Caption\', serif',
            '\'Proza Libre\', sans-serif'					=> '\'Proza Libre\', sans-serif',
            '\'Quicksand\', sans-serif'					=> '\'Quicksand\', sans-serif',
            '\'Raleway\', sans-serif'						=> '\'Raleway\', sans-serif',
            '\'Roboto\', sans-serif'						=> '\'Roboto\', sans-serif',
            '\'Roboto Condensed\', sans-serif'			=> '\'Roboto Condensed\', sans-serif',
            '\'Roboto Mono\', monospace'              => '\'Roboto Mono\', monospace',
            '\'Roboto Slab\', serif'						=> '\'Roboto Slab\', serif',
            '\'Rubik\', sans-serif'						   => '\'Rubik\', sans-serif',
            '\'Rubik Mono One\', sans-serif'				=> '\'Rubik Mono One\', sans-serif',
            '\'Share Tech Mono\', monospace'          => '\'Share Tech Mono\', monospace',
            '\'Slabo 13px\', serif'						   => '\'Slabo 13px\', serif',
            '\'Slabo 27px\', serif'						   => '\'Slabo 27px\', serif',
            '\'Space Mono\', monospace'               => '\'Space Mono\', monospace',
            '\'Spectral\', serif'							=> '\'Spectral\', serif',
            '\'Spectral SC\', serif'						=> '\'Spectral SC\', serif',
            '\'Source Sans Pro\', sans-serif'			=> '\'Source Sans Pro\', sans-serif',
            '\'Source Serif Pro\', serif'					=> '\'Source Serif Pro\', serif',
            '\'Titillium Web\', sans-serif'				=> '\'Titillium Web\', sans-serif',
            '\'Ubuntu\', sans-serif'						=> '\'Ubuntu\', sans-serif',
            '\'Ubuntu Mono\', monospace'              => '\'Ubuntu Mono\', monospace',
            '\'Work Sans\', sans-serif'					=> '\'Work Sans\', sans-serif',
            '\'Yatra One\', cursive'						=> '\'Yatra One\', cursive',
            );

            return $fonts;

 }


 